name: 🔴 IEEE Reviewer Feedback 
description: Tell us if there is missing or incorrect documentation
labels: [feedback]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue. Your feedback is highly valuable in ensuring the quality of our journal. 
        Please provide the following information to help us address the problem effectively:

  - type: dropdown
    attributes:
      label: What is the type of issue?
      multiple: true
      options:
        - Relevance
        - Validity
        - Significance/Original Contribution
        - Methodological Basis & Rigor
        - Clarity & Accessibility
        - Other (Please specify)
  - type: textarea
    attributes:
      label: What type of revision is this issue about?
      description: accepted for major or final 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevance
      description: Describe the relevance of the paper to the project
  - type: dropdown
    attributes:
      label: On a scale 1-5, how much relevant is it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: textarea
    attributes:
      label: Validity
      description: Describe the validity of the paper to the project
  - type: dropdown
    attributes:
      label: On a scale 1-5, how much relevant is it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: textarea
    attributes:
      label: Significance/Original Contribution
      description: Describe the significance or original contribution of the paper to the project
  - type: dropdown
    attributes:
      label: On a scale 1-5, how much relevant is it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: textarea
    attributes:
      label: Methodological Basis & Rigor
      description: Describe the methodological basis & rigor of the paper to the project
  - type: dropdown
    attributes:
      label: On a scale 1-5, how much relevant is it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: textarea
    attributes:
      label: Clarity & Accessibility
      description: Describe the clarity and accessibility of the paper to the project
  - type: dropdown
    attributes:
      label: On a scale 1-5, how much relevant is it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
  - type: textarea
    attributes:
      label: Comments to Author
      description: Overall comments to the paper
