name: Build LaTeX Document

on:
  push:
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v3
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: LaTeX-Documentation/run.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: LaTeX-Documentation/run.pdf
